### ISSUE TITLE
Requesting an Apple Silicon build

### ISSUE THREAD

**Issue by lextoumbourou** [vamp-plugins/vamp-plugin-pack#1]
As per the final comment on [this](https://github.com/sonic-visualiser/sonic-visualiser/issues/15) issue: _"Updated Vamp Plugin Pack is still pending, but that's a separate project..."_

I thought I might open an issue to express our interest in getting Vamp Plugin Pack working on Apple Silicon architectures. Happy for a universal binary as per sonic-visualiser.

**Comment by cannam** [comment]
Closed as completed - is there a universal binary that I don't know about? As far as I was aware this was still an open problem, as the existing plugins are Intel-only. They can be used with the ARM version of SV as they run in a separate process using Rosetta 2, but they are not ARM binaries.

**Comment by cannam** [comment]
The Vamp Plugin Pack v2 should now have universal builds of the plugins. Remaining problems should be opened as separate issues, I think.
